In [1]:
import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [2]:
type(list_[0])

str

In [8]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [5]:
array_list.dtype

dtype('<U1')

In [ ]:
Both are of same data type i.e. string

# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [37]:
import numpy as np
list_ = [ '1','2','3','4','5']
array_list = np.array(object = list_)
for i in range(len(list_)):
    print(type(list_[i]))
for i in range(array_list.size):
    print(array_list[i].dtype)
    


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<U1
<U1
<U1
<U1
<U1


# Q3. Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.

In [45]:
import numpy as np
list_ = [ '1','2','3','4','5']
array_list = np.array(object = list_,dtype=int)
print(type(list_[0]))
print(array_list.dtype)

<class 'str'>
int64


In [ ]:
yes, there is difference in the data types present in both the variables.

In [46]:
list_ = [ '1','2','3','4','5']
array_list = np.array(object = list_,dtype=int)
for i in range(len(list_)):
    print(type(list_[i]))
for i in range(array_list.size):
    print(array_list[i].dtype)

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
int64
int64
int64
int64
int64


In [47]:
# Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [48]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
num_array.size

6

In [52]:
num_array.shape

(2, 3)

# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [57]:
num_array1=np.zeros((3,3))

In [58]:
num_array1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
num_array1.size

9

In [60]:
num_array1.shape

(3, 3)

In [61]:
import numpy as np
num_array1=np.zeros((3,3))
print(num_array1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [64]:
import numpy.matlib as nm

In [65]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])